FinalProject/ViewModels/AllMedicalAnalysis.cs
namespace FinalProject.ViewModels
{
    public class AllMedicalAnalysis
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
}

FinalProject/ViewModels/CreateMedicalAnalysisViewModel.cs
namespace FinalProject.ViewModels
{
    public class CreateMedicalAnalysisViewModel
    {
        public int Id { get; set; }
        
        public string Name { get; set; }
    }
}

FinalProject/ViewModels/EditMedicalAnalysisViewModel.cs
namespace FinalProject.ViewModels
{
    public class EditMedicalAnalysisViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
}

FinalProject/Controllers/MedicalAnalysisController.cs
using FinalProject.IRepositry;
using FinalProject.Models;
using FinalProject.Repositry;
using FinalProject.Services;
using FinalProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Controllers
{
    public class MedicalAnalysisController : Controller
    {
        IMedicalAnalysisRepositry medicalAnalysisRepositry;
        UserManager<ApplicationUser> userManager;
        SignInManager<ApplicationUser> signIn;
        public MedicalAnalysisController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signIn,IMedicalAnalysisRepositry medicalAnalysisRepositry) 
        {
            this.userManager = userManager;
            this.signIn = signIn;
            this.medicalAnalysisRepositry = medicalAnalysisRepositry;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]

        [Authorize(Roles = "Admin")]
        public IActionResult CreateMedicalAnalysis()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        [Authorize(Roles = "Admin")]
        public IActionResult CreateMedicalAnalysis(CreateMedicalAnalysisViewModel createMedicalAnalysisView)
        {
            MedicalAnaylsis medicalAnaylsis = new MedicalAnaylsis() {Id = createMedicalAnalysisView.Id,Name = createMedicalAnalysisView.Name };
            medicalAnalysisRepositry.Create(medicalAnaylsis);
            return RedirectToAction("AllMedicalAnalysis");
        }
        public IActionResult AllMedicalAnalysis() 
        {
            List<AllMedicalAnalysis> medicalAnalyses=medicalAnalysisRepositry.GetAll().Select(MapRepositry.MapToAllMedicalAnalysisVM).ToList();
            return View(medicalAnalyses);
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult EditMedicalAnalysis(int id )
        {
            var editMedical = medicalAnalysisRepositry.GetById(id);
            EditMedicalAnalysisViewModel edit = new EditMedicalAnalysisViewModel() 
            { 
                Id = editMedical.Id,    
                Name = editMedical.Name

            };
            return View(edit);
        }
        [HttpPost]
        public IActionResult EditMedicalAnalysis(EditMedicalAnalysisViewModel editMedicalAnalysis) 
        {
            if (ModelState.IsValid)
            {
                medicalAnalysisRepositry.UpdateEdit(editMedicalAnalysis);
                return RedirectToAction("AllMedicalAnalysis");
            }
            return View(editMedicalAnalysis);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            medicalAnalysisRepositry.Delete(id);
            return RedirectToAction("AllMedicalAnalysis");
        }
        public IActionResult MedicalAnalysisDetalis(int id)
        {
            var details = medicalAnalysisRepositry.GetById(id);
            MedicalAnalysisDetailsViewModel detailsViewModel = new MedicalAnalysisDetailsViewModel()
            { 
                Id = details.Id,
                Name = details.Name,
            };
            return View(detailsViewModel);
        }
    }
}

FinalProject/Views/MedicalAnalysis/AllMedicalAnalysis.cshtml
@model IEnumerable<FinalProject.ViewModels.AllMedicalAnalysis>

@{
    ViewData["Title"] = "AllMedicalAnalysis";
    Layout = "_AdminLayout";
}


<a class="btn btn-primary btn-lg" role="button" asp-action="CreateMedicalAnalysis" asp-controller="MedicalAnalysis">
    <i class="bi bi-person-add"></i>
    Add new Medical Analysis

</a>
<br></br>
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/Dashboard/AdminIndex">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="#">MedicalAnalysis List</a></li>

</ol>

<div class="card border-primary mb-3" style="width:100%; max-height: 20rem; border:none">

    <div class="card-body">
        <h2 class="card-title">All MedicalAnalysis</h2>

    </div>
    
</div>


<table class="table table-hover">
    <thead>
        <tr class="table-primary">
            <th scope="row">Id</th>
            <td>Name</td>
            <td>Action</td>


        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td scope="row">
                    @Html.DisplayFor(modelItem => item.Id)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>

                <td>
                    <a asp-action="MedicalAnalysisDetalis" asp-controller="MedicalAnalysis" asp-route-id="@item.Id">
                        <i class="bi bi-eye"></i>
                    </a>
                    <a asp-action="EditMedicalAnalysis" asp-controller="MedicalAnalysis" asp-route-id="@item.Id">
                        <i class="bi bi-pencil-square"></i>
                    </a>
                    <a href="#" class="delete-item" data-id="@item.Id ">

                        <i class="bi bi-trash"></i>
                    </a>
                </td>

            </tr>

        }

    </tbody>
</table>


<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Confirm Delete</h5>
                <button type="button" class="close" id="close-modal-1" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete Medical Analysis ?</p>
            </div>
            <div class="modal-footer">
                <button type="button" id="close-modal-2" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a href="#" class="btn btn-danger confirm-delete" id="Delete" data-dismiss="modal">Delete</a>
            </div>
        </div>
    </div>
</div>





<script>
    // Select all elements with the class containing "delete" (assuming your class name includes "delete")
    const deleteLinks = document.querySelectorAll('.delete-item');
    deleteLinks.forEach(link => {
        link.addEventListener('click', function (event) {
            event.preventDefault(); // Prevent default navigation
            // Get item ID from the data-id attribute
            const itemId = this.dataset.id;
            // Logic to show the modal with the captured ID
            console.log(itemId);
            console.log(itemId)
            $("#itemId").val(itemId);
            $("#deleteModal").data("itemId", itemId); // Set ID as data attribute on modal button
            $("#deleteModal").modal("show");      //     Show the modal
            document.getElementById("Delete").href = "/MedicalAnalysis/Delete?id=" + itemId;
        });
    });
    // Close modal using close buttons
    const closeButtons = document.querySelectorAll('.close, .btn-secondary'); // Select both close buttons
    closeButtons.forEach(button => {
        button.addEventListener('click', function () {
            const deleteModal = document.getElementById('deleteModal');
            deleteModal.classList.remove('show'); // Hide the modal using Bootstrap class
        });
    });
</script>

FinalProject/Views/MedicalAnalysis/CreateMedicalAnalysis.cshtml
@model FinalProject.ViewModels.CreateMedicalAnalysisViewModel

@{
    ViewData["Title"] = "CreateMedicalAnalysis";
    Layout = "_AdminLayout";
}

<h1>MedicalAnalysis informations</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateMedicalAnalysis">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalProject/Views/MedicalAnalysis/EditMedicalAnalysis.cshtml
@model FinalProject.ViewModels.EditMedicalAnalysisViewModel

@{
    ViewData["Title"] = "EditMedicalAnalysis";
    Layout = "_AdminLayout";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a style="text-decoration:none" asp-action="AdminIndex" asp-controller="Dashboard">Dashboard</a></li>
        <li class="breadcrumb-item"><a style="text-decoration:none" asp-action="AllMedicalAnalysis" asp-controller="MedicalAnalysis">Medical Analysis</a></li>
        <li class="breadcrumb-item active" aria-current="page">Edit MedicalAnalysis Info</li>
    </ol>
</nav>
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditMedicalAnalysis">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalProject/Views/MedicalAnalysis/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "_Adminlayout";
}
<a asp-action="CreateMedicalAnalysis" asp-controller="MedicalAnalysis">Add new Medical Analysis</a>

FinalProject/Views/MedicalAnalysis/MedicalAnalysisDetalis.cshtml
@model MedicalAnalysisDetailsViewModel

@{
    Layout = "_AdminLayout";

}
<div class="card border-primary mb-3" style="width:100%; max-height: 20rem; border:none">


    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/Dashboard/AdminIndex">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="/Drug/AllDrug">Medical Analysis List</a></li>
        <li class="breadcrumb-item"><a href="#">Medical Analysis Info</a></li>

    </ol>
</div>

<div class="card text-center mx-auto" style="max-width: 600px;">
    <div class="card-body">
        <h3 class="card-title mb-4  text-primary"> Medical AnalysisInfo</h3>
        <hr />
        <div class="doc-info-body">
            <div class="doc-info-item">
                <ul class="list-unstyled d-grid gap-10">
                    <li class="d-sm-flex">
                        <i class="fas fa-user me-2 text-primary"></i>
                        <span class="fw-bold doc-info-title">Name</span>
                        <span class="fw-bold d-inline-block me-10"> : </span>
                        <span class="fs-base">@Model?.Name</span>
                    </li>
                    

                </ul>
            </div>
        </div>
    </div>
</div>