FinalProject/Models/Drug.cs
using System.ComponentModel.DataAnnotations;

namespace FinalProject.Models
{
    public class Drug
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; } 
        public string Description { get; set; }
        [Required]
        public double? Cost { get; set; }
        public int CompanyId { get; set; }

        public Company Company { get; set; }
        public ICollection<Prescription> Prescriptions { get; set; }
    }
}

FinalProject/ViewModels/AllDrugViewModel.cs
using FinalProject.Models;

namespace FinalProject.ViewModels
{
    public class AllDrugViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public double? Cost { get; set; }
        public string CompanyName { get; set; }
    }
}

FinalProject/ViewModels/CreateDrugViewModel.cs
using FinalProject.Models;
using System.ComponentModel.DataAnnotations;

namespace FinalProject.ViewModels
{
    public class CreateDrugViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }

        public double Cost { get; set; }
        [Display(Name = "Company")]
        public int CompanyId { get; set; }


    }
}

FinalProject/ViewModels/DrugDetailsViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace FinalProject.ViewModels
{
    public class DrugDetailsViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }

        public double? Cost { get; set; }
       
       
        public int CompanyId { get; set;}
        public string Company { get; set; }
    }
}

FinalProject/ViewModels/DrugViewModel.cs
namespace FinalProject.ViewModels
{
    public class DrugViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Instructions { get; set; }
    
    }
}

FinalProject/ViewModels/EditDrugViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace FinalProject.ViewModels
{
    public class EditDrugViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double? Cost { get; set; }

        [Display(Name = "Company")]
        public int CompanyId { get; set; }

    }
}

FinalProject/Controllers/DrugController.cs
using FinalProject.IRepositry;
using FinalProject.Models;
using FinalProject.Repositry;
using FinalProject.Services;
using FinalProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Controllers
{
    public class DrugController : Controller
    {
        IDrugRepositry drugRepositry;
        UserManager<ApplicationUser> userManager;
        SignInManager<ApplicationUser> signIn;
        ICompanyRepositry companyRepositry;

        public DrugController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signIn, IDrugRepositry drugRepositry, ICompanyRepositry companyRepositry)
        {
            this.userManager = userManager;
            this.signIn = signIn;
            this.drugRepositry = drugRepositry;
            this.companyRepositry = companyRepositry;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]

        [Authorize(Roles = "Admin")]
        public IActionResult CreateDrug()
        {
            ViewBag.Company = companyRepositry.GetAll();

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        [Authorize(Roles = "Admin")]
        public IActionResult CreateDrug(CreateDrugViewModel createDrugView)
        {
            if (ModelState.IsValid)
            {
                Drug drug = new Drug() { Id = createDrugView.Id, Name = createDrugView.Name, Description = createDrugView.Description, Cost = createDrugView.Cost, CompanyId = createDrugView.CompanyId };
                drugRepositry.Create(drug);
               
                return RedirectToAction("AllDrug");
            }
            return View();
        }

        public IActionResult AllDrug()
        {
            List<AllDrugViewModel> Drug = drugRepositry.GetAll().Select(MapRepositry.MapRoAllDrugVM).ToList();
            return View(Drug);
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult EditDrug(int id) 
        {
            var editDrug = drugRepositry.GetById(id);
            EditDrugViewModel editDrugView = new EditDrugViewModel()
            {
                Id = editDrug.Id,
                Name = editDrug.Name,
                Cost = editDrug.Cost,
                Description = editDrug.Description,
                CompanyId = editDrug.CompanyId
                
            };
            ViewBag.Company = companyRepositry.GetAll();

            return View(editDrugView);
        }
        [HttpPost]
        public IActionResult EditDrug(EditDrugViewModel editDrugView) 
        {
            if (ModelState.IsValid)
            {
                drugRepositry.UpdateEditDrug(editDrugView);
                return RedirectToAction("AllDrug");
            }

            return View(editDrugView);
            
        }

        [Authorize(Roles = "Admin")]
        public IActionResult DeleteDrug(int id)
        {
            drugRepositry.Delete(id);
            return RedirectToAction("AllDrug");
        }
        public IActionResult DrugDetalis(int id)
        {
            var detalis = drugRepositry._GetByIdUser(id);
            DrugDetailsViewModel drugDetailsViewModel = new DrugDetailsViewModel()
            {
                Id = id,
                Name = detalis.Name,
                Cost = detalis.Cost,
                Description = detalis.Description,
                Company = detalis.Company.Name
            };
           
            return View(drugDetailsViewModel);
        }
    }
}

FinalProject/Views/Drug/AllDrug.cshtml
@model IEnumerable<FinalProject.ViewModels.AllDrugViewModel>

@{
    ViewData["Title"] = "AllDrug";
    Layout = "_AdminLayout";
}


<a class="btn btn-primary btn-lg" role="button" asp-action="CreateDrug" asp-controller="Drug">
    <i class="bi bi-person-add"></i>
    Add new Drug

</a>
<br></br>
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/Dashboard/AdminIndex">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="#">Drug List</a></li>

</ol>

<div class="card border-primary mb-3" style="width:100%; max-height: 20rem; border:none">

    <div class="card-body">
        <h2 class="card-title">All Drug</h2>

    </div>
   
</div>


<table class="table table-hover">
    <thead>
        <tr class="table-primary">
            <th scope="row">Id</th>
            <td>Name</td>
            <td>Cost</td>
            <td>Company</td>
            <td>Action</td>


        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td scope="row">
                    @Html.DisplayFor(modelItem => item.Id)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Cost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyName)
                </td>

                <td>
                    <a asp-action="DrugDetalis" asp-controller="Drug" asp-route-id="@item.Id">
                        <i class="bi bi-eye"></i>
                    </a>
                    <a asp-action="EditDrug" asp-controller="Drug" asp-route-id="@item.Id">
                        <i class="bi bi-pencil-square"></i>
                    </a>
                    <a href="#" class="delete-item" data-id="@item.Id ">
                        @*  <a asp-action="DeletePatient" asp-controller="patient" asp-route-id="@patient.Id"> *@
                        <i class="bi bi-trash"></i>
                    </a>
                </td>

            </tr>

        }

    </tbody>
</table>


<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Confirm Delete</h5>
                <button type="button" class="close" id="close-modal-1" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete the Drug ?</p>
            </div>
            <div class="modal-footer">
                <button type="button" id="close-modal-2" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a href="#" class="btn btn-danger confirm-delete" id="Delete" data-dismiss="modal">Delete</a>
            </div>
        </div>
    </div>
</div>





<script>
    // Select all elements with the class containing "delete" (assuming your class name includes "delete")
    const deleteLinks = document.querySelectorAll('.delete-item');
    deleteLinks.forEach(link => {
        link.addEventListener('click', function (event) {
            event.preventDefault(); // Prevent default navigation
            // Get item ID from the data-id attribute
            const itemId = this.dataset.id;
            // Logic to show the modal with the captured ID
            console.log(itemId);
            console.log(itemId)
            $("#itemId").val(itemId);
            $("#deleteModal").data("itemId", itemId); // Set ID as data attribute on modal button
            $("#deleteModal").modal("show");      //     Show the modal
            document.getElementById("Delete").href = "/Drug/DeleteDrug?id=" + itemId;
        });
    });
    // Close modal using close buttons
    const closeButtons = document.querySelectorAll('.close, .btn-secondary'); // Select both close buttons
    closeButtons.forEach(button => {
        button.addEventListener('click', function () {
            const deleteModal = document.getElementById('deleteModal');
            deleteModal.classList.remove('show'); // Hide the modal using Bootstrap class
        });
    });
</script>

FinalProject/Views/Drug/CreateDrug.cshtml
@model FinalProject.ViewModels.CreateDrugViewModel

@{
    ViewData["Title"] = "CreateDrug";
    SelectList CompanyList = new SelectList(ViewBag.Company, "Id", "Name");
    Layout = "_AdminLayout";
}

<h1>Drug Information</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateDrug">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cost" class="control-label"></label>
                <input asp-for="Cost" class="form-control" />
                <span asp-validation-for="Cost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyId"></label>
                <select asp-for="CompanyId" class="form-control" asp-items="CompanyList" placeholder="Enter Company "></select>
                <span asp-validation-for="CompanyId" class="text-danger"></span>

            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

FinalProject/Views/Drug/DrugDetails.cshtml
@model DrugDetailsViewModel

@{
    Layout = "_AdminLayout";
}
<div class="card border-primary mb-3" style="width:100%; max-height: 20rem; border:none">


    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/Dashboard/AdminIndex">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="/Drug/AllDrug">Drug List</a></li>
        <li class="breadcrumb-item"><a href="#">Drug Info</a></li>

    </ol>
</div>

<div class="card text-center mx-auto" style="max-width: 600px;">
    <div class="card-body">
        <h3 class="card-title mb-4  text-primary">Drug Info</h3>
        <hr />
        <div class="doc-info-body">
            <div class="doc-info-item">
                <ul class="list-unstyled d-grid gap-10">

                    <li class="d-sm-flex">
                        <i class="fas fa-user-md me-2 text-primary"></i>
                        <span class="fw-bold doc-info-title">Name</span>
                        <span class="fw-bold d-inline-block me-10"> : </span>
                        <span class="fs-base">@Model?.Name</span>
                    </li>
                    <br />
                    <li class="d-sm-flex">
                        <i class="fas fa-user-md me-2 text-primary"></i>
                        <span class="fw-bold doc-info-title">Cost</span>
                        <span class="fw-bold d-inline-block me-10"> : </span>
                        <span class="fs-base">@Model?.Cost</span>
                    </li>
                    <br />
                    <li class="d-sm-flex">
                        <i class="fas fa-map-marker-alt me-2 text-primary"></i>
                        <span class="fw-bold doc-info-title">Description</span>
                        <span class="fw-bold d-inline-block me-10"> : </span>
                        <span class="fs-base">@Model?.Description</span>
                    </li>
                    <br />
                    <li class="d-sm-flex">
                        <i class="fas fa-city me-2 text-primary"></i>
                        <span class="fw-bold doc-info-title">CompanyName</span>
                        <span class="fw-bold d-inline-block me-10"> : </span>
                        <span class="fs-base">@Model?.CompanyId </span>
                    </li>


                </ul>
            </div>
        </div>
    </div>
</div>

FinalProject/Views/Drug/DrugDetalis.cshtml
@model DrugDetailsViewModel

@{
    Layout = "_AdminLayout";
   
}
<div class="card border-primary mb-3" style="width:100%; max-height: 20rem; border:none">


    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/Dashboard/AdminIndex">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="/Drug/AllDrug">Drug List</a></li>
        <li class="breadcrumb-item"><a href="#">Drug Info</a></li>

    </ol>
</div>

<div class="card text-center mx-auto" style="max-width: 600px;">
    <div class="card-body">
        <h3 class="card-title mb-4  text-primary">Drug Info</h3>
        <hr />
        <div class="doc-info-body">
            <div class="doc-info-item">
                <ul class="list-unstyled d-grid gap-10">
                    <li class="d-sm-flex">
                        <i class="fas fa-user me-2 text-primary"></i>
                        <span class="fw-bold doc-info-title">Name</span>
                        <span class="fw-bold d-inline-block me-10"> : </span>
                        <span class="fs-base">@Model?.Name</span>
                    </li>
                    <br />
                    <li class="d-sm-flex">
                        <i class="fas fa-dollar-sign me-2 text-primary"></i>
                        <span class="fw-bold doc-info-title">Cost</span>
                        <span class="fw-bold d-inline-block me-10"> : </span>
                        <span class="fs-base">@Model?.Cost</span>
                    </li>
                    <br />
                    <li class="d-sm-flex">
                        <i class="fas fa-align-left me-2 text-primary"></i>
                        <span class="fw-bold doc-info-title">Description</span>
                        <span class="fw-bold d-inline-block me-10"> : </span>
                        <span class="fs-base">@Model?.Description</span>
                    </li>
                    <br />
                    <li class="d-sm-flex">
                        <i class="fas fa-building me-2 text-primary"></i>
                        <span class="fw-bold doc-info-title">CompanyName</span>
                        <span class="fw-bold d-inline-block me-10"> : </span>
                        <span class="fs-base">@Model?.Company</span>
                    </li>

                </ul>
            </div>
        </div>
    </div>
</div>

FinalProject/Views/Drug/EditDrug.cshtml
@model FinalProject.ViewModels.EditDrugViewModel

@{
    ViewData["Title"] = "EditDrug";
    SelectList CompanyList = new SelectList(ViewBag.Company, "Id", "Name");
    Layout = "_AdminLayout";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a style="text-decoration:none" asp-action="AdminIndex" asp-controller="Dashboard">Dashboard</a></li>
        <li class="breadcrumb-item"><a style="text-decoration:none" asp-action="AllDrug" asp-controller="Drug">Drugs</a></li>
        <li class="breadcrumb-item active" aria-current="page">Edit Drug Info</li>
    </ol>
</nav>
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditDrug">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cost" class="control-label"></label>
                <input asp-for="Cost" class="form-control" />
                <span asp-validation-for="Cost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyId"></label>
                <select asp-for="CompanyId" class="form-control" asp-items="CompanyList"></select>
                <span asp-validation-for="CompanyId" class="text-danger"></span>

            </div>
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalProject/Views/Drug/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "_Adminlayout";
}
<a asp-action="CreateDrug" asp-controller="Drug">Add new Drug</a>